name: release 
on:
  release:
    type: [publish]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: testecho
        run: echo ${GITHUB_REF##}     
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/tags/{tag}
          owner: dguodev
          repo: whatismyip
          tag: ${GITHUB_REF##*/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"
